#!/bin/bash
# MongoDB Atlas + Vercel Deployment Setup

echo "🚀 Classroom Assistant - MongoDB Atlas Setup"
echo "==========================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  Go to: https://www.mongodb.com/cloud/atlas"
echo "   - Create FREE account"
echo "   - Create Shared cluster"
echo "   - Add Database User (username: classroom)"
echo "   - Allow Network Access from anywhere (0.0.0.0/0)"
echo ""
echo "2️⃣  Get Connection String:"
echo "   - Click Connect → Drivers → Node.js"
echo "   - Copy the connection string"
echo "   - Replace PASSWORD with your database password"
echo ""
echo "3️⃣  Update backend/.env:"
echo "   MONGODB_URI=mongodb+srv://classroom:YOUR_PASSWORD@cluster.mongodb.net/"
echo "   DATABASE_NAME=classroomassisstant"
echo ""
echo "4️⃣  Test locally:"
echo "   cd backend"
echo "   python app.py"
echo ""
echo "5️⃣  Add to Vercel Backend Project:"
echo "   Settings → Environment Variables"
echo "   - MONGODB_URI"
echo "   - DATABASE_NAME"
echo "   - JWT_SECRET"
echo "   - GOOGLE_CLIENT_ID"
echo ""
echo "6️⃣  Redeploy on Vercel:"
echo "   - Backend: Deployments → Redeploy"
echo "   - Frontend: Deployments → Redeploy"
echo ""
echo "7️⃣  Test at:"
echo "   https://real-time-classroom-assistant-ye11.vercel.app"
echo ""
echo "📚 For detailed guide: See MONGODB_ATLAS_SETUP.md"
